version: '3.4'

services:
  bonds.app.api:
    image: ${DOCKER_REGISTRY-}bondsappapi
    build:
      context: .
      dockerfile: Bonds.App.Api/Dockerfile
    environment:
      - ConnectionStrings__Bonds=Server=postgres;Port=5432;User Id=admin;Password=admin;Database=bonds;

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always